### PR TITLE
Small bug in difflib.

### PR DESCRIPTION
**Pull request by wookenny**
Hi Jean-Bernard,

I found and fixed two issues in you difflib code:
- added a destr. to delete the allicated memory for 'matching_blocks_'
- clearing 'b2j_' in chain_b() 

I had to change instantiation to be able to compile the code.
My observation was that  some memory was lost, the destr. fixed that. 
Furthermore, I changed the testcases. If you do not clear b2j_, the matches are wrong.
E.g.,  For "Hello Roger" and "Hello Peter" the block  'Roge' and 'eter' is found, in numbers (6 7 4).

Thanks for this great implementation, I intend to add ratio() for a similarity test.

Best,
Torsten

### CODE REVIEW

**Comment by duckie** [comment]
Hi wookenny

I just saw your proposal, thank you very much. My implementation is rather incomplete, you ratio() implementation is welcome.

**Comment by duckie** [comment]
Just so you know, you dont need to test matching_blocks before deletion. The delete operator makes this test itself before deleting anything, its correct to call delete on a null pointer. Either way, I think I'll replace the raw pointer with a unique_ptr to guarantee good behavior.

**Comment by wookenny** [comment]
Hi duckie,

a small thing I should mention. I tested the speed of your implementation. Either I'm using it wrong or it is way too slow:

1000 similarity comparisions on two text files:
python code: 0m4.965s       sim: 0.879375180793
difflib.h:         0m42.064s     sim: 0.970303

I tried a real simple C++11 implementation of the needed parts of pythons difflib for this. No templates involved. Just plain std::string references.
result:        0m0.898s         sim: 0.879153

Both c++ files were compiled with -03.
The execution looked like this: 

---

## difflib.h

auto matcher = difflib::MakeSequenceMatcher<>(a, b);
for(uint i=0; i<1000; ++i){
    matcher.set_seq1(a);
    ratio = matcher.ratio();
}
std::cout<< ratio <<std::endl;

---

## python 

for i in range(1,1001):
    s = difflib.SequenceMatcher()
"""had to do  call set_seqs with swapped argument each time
otherwise the computation is much faster due to prev. stored  computations"""
    if(i%2==0):
        s.set_seqs(a,b) 
    else:
        s.set_seqs(b,a)  
    r = s.ratio()
print r    

---

I'm on vacation soon, but I will try to find the error in the template code when I'm back. 
Maybe I'm using it wrong. I use this Code to compare a lot of text files with each other to find parts that are copied. So clearly speed is an issue here for me.

Best,
Torsten

**Comment by duckie** [comment]
I opened a issue about this. https://github.com/duckie/difflib/issues/2 Will take a look very soon.

**Comment by duckie** [comment]
Hi Torsten

With the last improvements, you should not have cases of C++ optimized code running slower than the python version. It should at least ten times faster (or faster, depending on the input data). The particular case of the strings is interesting for performance comparisons because the hash computation have no cost at all.

Edit: Notice that you can get amazing performances on the python version witg pypy. The C++ version is still faster though.

I would really like to see how it behaves againts your "not templated" version, if you have time enough to run your test again with the latest version :). I mean with the master branch, the experimental one does not work.

Regards

**Comment by wookenny** [comment]
Works like a charm. Just to give you some numbers from my current tests, here are the running times of four versions. First the diff is done by python, then the slow version, an impromptu implementation of the needed parts I did for comparision and the latest version.

This time, compiled with g++ using -O2

Running time: 
python:       11.31 s
pypy:            1.70 s
old difflib:  163.92 s
my test:         2.96 s
new difflib:     0.73 s

So, well done and thanks a lot. The speed is much more reasonable now. :+1:

**Pull request merged**
